/**
 * Route Exports
 *
 * Minimal route exports - most CRUD routes are now auto-generated
 * by @dotdo/apis database convention in api/index.ts.
 *
 * Only custom routes (health, AI) are exported here.
 */

// Custom routes that are NOT auto-generated by convention
export { createHealthRoutes } from './health'
export { createAIRoutes } from './ai'
