/**
 * Schema Types
 *
 * Types for SchemaManager and database schema definitions.
 * Used by SchemaManager for table initialization and versioning.
 */

/**
 * Schema version information
 */
export interface SchemaVersion {
  /** Schema version number */
  version: number
  /** When the schema was first created */
  createdAt: Date
  /** When the schema was last updated */
  updatedAt: Date
}

/**
 * Column definition for a table
 */
export interface ColumnDefinition {
  /** Column name */
  name: string
  /** SQL data type (TEXT, INTEGER, etc.) */
  type: string
  /** Whether the column allows NULL values */
  nullable: boolean
  /** Default value expression */
  defaultValue?: string
  /** Whether the column is unique */
  unique?: boolean
}

/**
 * Index definition for a table
 */
export interface IndexDefinition {
  /** Index name */
  name: string
  /** Columns included in the index */
  columns: string[]
  /** Whether the index enforces uniqueness */
  unique?: boolean
}

/**
 * Table definition
 */
export interface TableDefinition {
  /** Table name */
  name: string
  /** Column definitions */
  columns: ColumnDefinition[]
  /** Primary key column(s) */
  primaryKey: string[]
  /** Index definitions */
  indexes?: IndexDefinition[]
}

/**
 * Migration definition for schema evolution
 */
export interface Migration {
  /** Migration version number (must be unique) */
  version: number
  /** Human-readable migration name */
  name: string
  /** SQL to apply the migration */
  up: string
  /** SQL to reverse the migration (optional for irreversible migrations) */
  down?: string
}

/**
 * Result of a migration operation
 */
export interface MigrationResult {
  /** Migration version that was processed */
  version: number
  /** Migration name */
  name: string
  /** Status of the migration */
  status: 'applied' | 'rolled_back' | 'failed' | 'skipped'
  /** Time taken to execute in milliseconds */
  executionTime: number
  /** When the migration was applied/rolled back */
  appliedAt: Date
  /** Error message if failed */
  error?: string
}

/**
 * Entry in the migration history table
 */
export interface MigrationHistoryEntry {
  /** Migration version */
  version: number
  /** Migration name */
  name: string
  /** When the migration was applied */
  appliedAt: Date
  /** Checksum of migration SQL for validation */
  checksum: string
  /** Time taken to execute in milliseconds */
  executionTime: number
  /** Current status */
  status: 'applied' | 'rolled_back' | 'failed'
}
/**
 * @dotdo/do - Schema Validation Types
 *
 * Core types and base classes for the schema validation system.
 * Provides a foundation for building type-safe runtime validators.
 */

// =============================================================================
// JSON Schema Types
// =============================================================================

/**
 * Represents a JSON Schema object (subset of JSON Schema draft 2020-12).
 */
export interface JSONSchema {
  $schema?: string
  $comment?: string
  type: string
  description?: string
  examples?: unknown[]
  properties?: Record<string, JSONSchema>
  required?: string[]
  additionalProperties?: boolean
  items?: JSONSchema
}

// =============================================================================
// AI Metadata Types
// =============================================================================

/**
 * Metadata for AI-assisted generation of values.
 * These hints guide AI generators in producing appropriate content.
 */
export interface AIMetadata {
  /** Human-readable description of what this field represents */
  description?: string
  /** Example values for the AI to learn from */
  examples?: unknown[]
  /** Whether this field should be auto-generated by AI */
  generate?: boolean
  /** Maximum length for generated strings */
  maxLength?: number
  /** Minimum length for generated strings */
  minLength?: number
  /** Number of items to generate for arrays */
  count?: number
  /** Minimum value for numbers */
  min?: number
  /** Maximum value for numbers */
  max?: number
  /** Custom prompt for AI generation */
  prompt?: string
  /** Format hint (e.g., 'email', 'url', 'uuid') */
  format?: string
  /** Whether to cascade generate related entities */
  cascade?: boolean
}

// =============================================================================
// Validation Result Types
// =============================================================================

/**
 * Represents an error that occurred during validation.
 *
 * @example
 * ```typescript
 * const error: ValidationError = {
 *   path: ['user', 'email'],
 *   message: 'Expected string',
 *   code: 'invalid_type'
 * }
 * ```
 */
export interface ValidationError {
  /** The path to the property that failed validation (e.g., ['user', 'email']) */
  path: string[]
  /** Human-readable error message describing the validation failure */
  message: string
  /** Machine-readable error code for programmatic handling */
  code: string
}

/**
 * Discriminated union result type for validation operations.
 * Either succeeds with typed data or fails with an array of errors.
 *
 * @typeParam T - The expected type of the validated data
 *
 * @example
 * ```typescript
 * const result: ValidationResult<string> = schema.validate(input)
 * if (result.success) {
 *   console.log(result.data) // typed as string
 * } else {
 *   console.error(result.errors) // ValidationError[]
 * }
 * ```
 */
export type ValidationResult<T = unknown> =
  | { success: true; data: T; errors?: undefined }
  | { success: false; data?: undefined; errors: ValidationError[] }

// =============================================================================
// Base Type Class
// =============================================================================

/**
 * Abstract base class for all schema types.
 *
 * Provides common validation patterns, utility methods, and a foundation
 * for method chaining in derived types.
 *
 * @typeParam T - The output type this schema produces after successful validation
 *
 * @example
 * ```typescript
 * class CustomType extends BaseType<MyType> {
 *   validate(value: unknown): ValidationResult<MyType> {
 *     // Custom validation logic
 *   }
 * }
 * ```
 */
export abstract class BaseType<T = unknown> {
  /**
   * Indicates whether this schema handles undefined values (e.g., default, optional).
   * Used by RequiredType to determine whether to check for undefined before or after
   * delegating to the inner schema.
   *
   * @protected
   */
  protected readonly handlesUndefined: boolean = false

  /**
   * AI generation hints for this schema type.
   * @protected
   */
  protected aiHints?: AIMetadata

  /**
   * Description for this schema type (for JSON Schema output).
   * @protected
   */
  protected _description?: string

  /**
   * Example values for this schema type (for JSON Schema output).
   * @protected
   */
  protected _examples?: T[]

  /**
   * Validates the given value against this schema type.
   *
   * @param value - The value to validate (can be any type)
   * @returns A ValidationResult indicating success with typed data or failure with errors
   */
  abstract validate(value: unknown): ValidationResult<T>

  /**
   * Adds AI generation hints to this schema type.
   * Hints are merged with any existing hints.
   *
   * @param hints - AI metadata hints for generation
   * @returns This schema type (for method chaining)
   *
   * @example
   * ```typescript
   * $.string().ai({ description: 'Full name', examples: ['John Doe'] })
   * $.array($.string()).ai({ generate: true, count: 5 })
   * ```
   */
  ai(hints: AIMetadata): this {
    this.aiHints = this.aiHints ? { ...this.aiHints, ...hints } : { ...hints }
    return this
  }

  /**
   * Gets the AI generation hints for this schema type.
   *
   * @returns The AI metadata hints, or undefined if none are set
   */
  getAIHints(): AIMetadata | undefined {
    return this.aiHints
  }

  /**
   * Sets a description for this schema type.
   * The description is included in JSON Schema output.
   *
   * @param description - Human-readable description of this type
   * @returns This schema type (for method chaining)
   *
   * @example
   * ```typescript
   * $.string().describe('Primary email address')
   * ```
   */
  describe(description: string): this {
    this._description = description
    return this
  }

  /**
   * Gets the description for this schema type.
   *
   * @returns The description, or undefined if none is set
   */
  getDescription(): string | undefined {
    return this._description
  }

  /**
   * Adds an example value for this schema type.
   * Examples are included in JSON Schema output.
   *
   * @param value - An example value for this type
   * @returns This schema type (for method chaining)
   *
   * @example
   * ```typescript
   * $.string().example('admin')
   * ```
   */
  example(value: T): this {
    if (!this._examples) {
      this._examples = []
    }
    this._examples.push(value)
    return this
  }

  /**
   * Gets the example values for this schema type.
   *
   * @returns The example values, or undefined if none are set
   */
  getExamples(): T[] | undefined {
    return this._examples
  }

  /**
   * Creates a successful validation result with the validated data.
   *
   * @param data - The validated and typed data
   * @returns A success ValidationResult containing the data
   * @protected
   */
  protected success(data: T): ValidationResult<T> {
    return { success: true, data }
  }

  /**
   * Creates a failed validation result with error details.
   *
   * @param message - Human-readable error message
   * @param code - Machine-readable error code (e.g., 'invalid_type', 'required')
   * @param path - Path to the property that failed (defaults to root [])
   * @returns A failure ValidationResult containing the error
   * @protected
   */
  protected failure(message: string, code: string, path: string[] = []): ValidationResult<T> {
    return {
      success: false,
      errors: [{ path, message, code }],
    }
  }

  /**
   * Creates a failure result with multiple errors.
   *
   * @param errors - Array of validation errors
   * @returns A failure ValidationResult containing all errors
   * @protected
   */
  protected failures(errors: ValidationError[]): ValidationResult<T> {
    return { success: false, errors }
  }

  // ==========================================================================
  // Modifier Methods
  // ==========================================================================

  /**
   * Makes this schema required, rejecting undefined values.
   *
   * @returns A new schema that rejects undefined
   *
   * @example
   * ```typescript
   * $.string().required().validate(undefined)
   * // { success: false, errors: [{ code: 'required', ... }] }
   * ```
   */
  required(): RequiredType<T> {
    return new RequiredType(this)
  }

  /**
   * Makes this schema optional, allowing undefined values.
   *
   * @returns A new schema that accepts undefined
   *
   * @example
   * ```typescript
   * $.string().optional().validate(undefined)
   * // { success: true, data: undefined }
   * ```
   */
  optional(): OptionalType<T> {
    return new OptionalType(this)
  }

  /**
   * Provides a default value when the input is undefined.
   *
   * @param defaultValue - The default value or a function that returns it
   * @returns A new schema that substitutes the default for undefined
   *
   * @example
   * ```typescript
   * $.string().default('unknown').validate(undefined)
   * // { success: true, data: 'unknown' }
   * ```
   */
  default(defaultValue: T | (() => T)): DefaultType<T> {
    return new DefaultType(this, defaultValue)
  }

  /**
   * Transforms the validated value using a function.
   *
   * @typeParam U - The output type after transformation
   * @param fn - The transformation function
   * @returns A new schema that transforms valid values
   *
   * @example
   * ```typescript
   * $.string().transform(s => s.toUpperCase()).validate('hello')
   * // { success: true, data: 'HELLO' }
   * ```
   */
  transform<U>(fn: (value: T) => U): TransformType<T, U> {
    return new TransformType(this, fn)
  }
}

// =============================================================================
// Primitive Type Classes
// =============================================================================

/**
 * Schema type for validating string values.
 *
 * Validates that the input is a JavaScript string primitive.
 * Empty strings are considered valid.
 *
 * @example
 * ```typescript
 * const schema = new StringType()
 *
 * schema.validate('hello')  // { success: true, data: 'hello' }
 * schema.validate('')       // { success: true, data: '' }
 * schema.validate(123)      // { success: false, errors: [...] }
 * schema.validate(null)     // { success: false, errors: [...] }
 * ```
 */
export class StringType extends BaseType<string> {
  /**
   * Validates that the value is a string.
   *
   * @param value - The value to validate
   * @returns A ValidationResult with the string data or validation errors
   */
  validate(value: unknown): ValidationResult<string> {
    if (typeof value !== 'string') {
      return this.failure('Expected string', 'invalid_type')
    }
    return this.success(value)
  }
}

/**
 * Schema type for validating number values.
 *
 * Validates that the input is a JavaScript number primitive.
 * NaN is rejected, but Infinity and -Infinity are accepted.
 *
 * @example
 * ```typescript
 * const schema = new NumberType()
 *
 * schema.validate(42)       // { success: true, data: 42 }
 * schema.validate(3.14)     // { success: true, data: 3.14 }
 * schema.validate(0)        // { success: true, data: 0 }
 * schema.validate(-5)       // { success: true, data: -5 }
 * schema.validate(Infinity) // { success: true, data: Infinity }
 * schema.validate(NaN)      // { success: false, errors: [...] }
 * schema.validate('42')     // { success: false, errors: [...] }
 * ```
 */
export class NumberType extends BaseType<number> {
  /**
   * Validates that the value is a number (not NaN).
   *
   * @param value - The value to validate
   * @returns A ValidationResult with the number data or validation errors
   */
  validate(value: unknown): ValidationResult<number> {
    if (typeof value !== 'number' || Number.isNaN(value)) {
      return this.failure('Expected number', 'invalid_type')
    }
    return this.success(value)
  }
}

/**
 * Schema type for validating boolean values.
 *
 * Validates that the input is a JavaScript boolean primitive.
 * Does not coerce truthy/falsy values.
 *
 * @example
 * ```typescript
 * const schema = new BooleanType()
 *
 * schema.validate(true)     // { success: true, data: true }
 * schema.validate(false)    // { success: true, data: false }
 * schema.validate(1)        // { success: false, errors: [...] }
 * schema.validate('true')   // { success: false, errors: [...] }
 * ```
 */
export class BooleanType extends BaseType<boolean> {
  /**
   * Validates that the value is a boolean.
   *
   * @param value - The value to validate
   * @returns A ValidationResult with the boolean data or validation errors
   */
  validate(value: unknown): ValidationResult<boolean> {
    if (typeof value !== 'boolean') {
      return this.failure('Expected boolean', 'invalid_type')
    }
    return this.success(value)
  }
}

/**
 * Schema type for validating Date values.
 *
 * Validates Date objects and coerces ISO date strings to Date objects.
 * Invalid Date objects (where getTime() returns NaN) are rejected.
 *
 * @example
 * ```typescript
 * const schema = new DateType()
 *
 * schema.validate(new Date())            // { success: true, data: Date }
 * schema.validate('2024-01-15')          // { success: true, data: Date } (coerced)
 * schema.validate('2024-01-15T12:00:00Z') // { success: true, data: Date } (coerced)
 * schema.validate(new Date('invalid'))   // { success: false, errors: [...] }
 * schema.validate('not-a-date')          // { success: false, errors: [...] }
 * schema.validate(123)                   // { success: false, errors: [...] }
 * ```
 */
export class DateType extends BaseType<Date> {
  /**
   * Validates that the value is a valid Date or coercible ISO string.
   *
   * @param value - The value to validate
   * @returns A ValidationResult with the Date data or validation errors
   */
  validate(value: unknown): ValidationResult<Date> {
    // Handle Date objects
    if (value instanceof Date) {
      if (Number.isNaN(value.getTime())) {
        return this.failure('Expected valid date', 'invalid_type')
      }
      return this.success(value)
    }

    // Handle ISO date strings (coercion)
    if (typeof value === 'string') {
      const date = new Date(value)
      if (Number.isNaN(date.getTime())) {
        return this.failure('Expected valid date', 'invalid_type')
      }
      return this.success(date)
    }

    return this.failure('Expected date or ISO date string', 'invalid_type')
  }
}

// =============================================================================
// Modifier Type Classes
// =============================================================================

/**
 * Schema type that requires a value to be present (not undefined).
 *
 * Wraps another schema and rejects undefined values before
 * delegating to the inner schema for type validation.
 *
 * @typeParam T - The output type from the inner schema
 *
 * @example
 * ```typescript
 * const schema = new RequiredType(new StringType())
 *
 * schema.validate('hello')    // { success: true, data: 'hello' }
 * schema.validate(undefined)  // { success: false, errors: [{ code: 'required', ... }] }
 * ```
 */
export class RequiredType<T> extends BaseType<T> {
  constructor(private readonly inner: BaseType<T>) {
    super()
  }

  /**
   * Validates that the value is not undefined, with special handling for
   * inner schemas that handle undefined (like default() or optional()).
   *
   * - If inner schema handles undefined: delegate first, then check result
   * - Otherwise: check for undefined first, then delegate
   *
   * @param value - The value to validate
   * @returns A ValidationResult with the validated data or errors
   */
  validate(value: unknown): ValidationResult<T> {
    // Check if the inner schema handles undefined values (default, optional)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const innerHandlesUndefined = (this.inner as any).handlesUndefined === true

    if (innerHandlesUndefined) {
      // Let inner schema process the value first (allows default() to work)
      const result = this.inner.validate(value)

      // If inner validation failed, propagate the error
      if (!result.success) {
        return result
      }

      // Check if the result data is undefined (required check on output)
      if (result.data === undefined) {
        return this.failure('Value is required', 'required')
      }

      return result
    } else {
      // Check for undefined before delegating to inner schema
      if (value === undefined) {
        return this.failure('Value is required', 'required')
      }
      return this.inner.validate(value)
    }
  }
}

/**
 * Schema type that allows undefined values.
 *
 * Wraps another schema and passes undefined through without validation,
 * while delegating non-undefined values to the inner schema.
 *
 * @typeParam T - The output type from the inner schema
 *
 * @example
 * ```typescript
 * const schema = new OptionalType(new StringType())
 *
 * schema.validate('hello')    // { success: true, data: 'hello' }
 * schema.validate(undefined)  // { success: true, data: undefined }
 * schema.validate(123)        // { success: false, errors: [...] }
 * ```
 */
export class OptionalType<T> extends BaseType<T | undefined> {
  protected override readonly handlesUndefined = true

  constructor(private readonly inner: BaseType<T>) {
    super()
  }

  /**
   * Passes undefined through, otherwise delegates to inner schema.
   *
   * @param value - The value to validate
   * @returns A ValidationResult with the validated data or errors
   */
  validate(value: unknown): ValidationResult<T | undefined> {
    if (value === undefined) {
      return this.success(undefined)
    }
    return this.inner.validate(value) as ValidationResult<T | undefined>
  }
}

/**
 * Schema type that provides a default value when input is undefined.
 *
 * Wraps another schema and substitutes a default value for undefined,
 * while delegating non-undefined values to the inner schema.
 *
 * @typeParam T - The output type from the inner schema
 *
 * @example
 * ```typescript
 * const schema = new DefaultType(new StringType(), 'unknown')
 *
 * schema.validate('hello')    // { success: true, data: 'hello' }
 * schema.validate(undefined)  // { success: true, data: 'unknown' }
 * schema.validate(123)        // { success: false, errors: [...] }
 * ```
 */
export class DefaultType<T> extends BaseType<T> {
  protected override readonly handlesUndefined = true

  constructor(
    private readonly inner: BaseType<T>,
    private readonly defaultValue: T | (() => T)
  ) {
    super()
  }

  /**
   * Returns default value for undefined, otherwise delegates to inner schema.
   *
   * @param value - The value to validate
   * @returns A ValidationResult with the validated data or errors
   */
  validate(value: unknown): ValidationResult<T> {
    if (value === undefined) {
      const resolved =
        typeof this.defaultValue === 'function'
          ? (this.defaultValue as () => T)()
          : this.defaultValue
      return this.success(resolved)
    }
    return this.inner.validate(value)
  }
}

/**
 * Schema type that transforms validated values using a function.
 *
 * Wraps another schema and applies a transformation function to
 * successfully validated values. Invalid values are not transformed.
 *
 * @typeParam T - The input type from the inner schema
 * @typeParam U - The output type after transformation
 *
 * @example
 * ```typescript
 * const schema = new TransformType(new StringType(), s => s.toUpperCase())
 *
 * schema.validate('hello')  // { success: true, data: 'HELLO' }
 * schema.validate(123)      // { success: false, errors: [...] }
 * ```
 */
export class TransformType<T, U> extends BaseType<U> {
  constructor(
    private readonly inner: BaseType<T>,
    private readonly fn: (value: T) => U
  ) {
    super()
  }

  /**
   * Validates with inner schema, then transforms successful results.
   *
   * @param value - The value to validate
   * @returns A ValidationResult with the transformed data or errors
   */
  validate(value: unknown): ValidationResult<U> {
    const result = this.inner.validate(value)
    if (!result.success) {
      return result as unknown as ValidationResult<U>
    }
    return this.success(this.fn(result.data))
  }
}

// =============================================================================
// Composite Type Classes
// =============================================================================

/**
 * Schema type for validating arrays.
 *
 * Validates that the input is an array and validates each item
 * against the provided item schema.
 *
 * @typeParam T - The type of items in the array
 *
 * @example
 * ```typescript
 * const schema = new ArrayType(new StringType())
 *
 * schema.validate(['a', 'b'])  // { success: true, data: ['a', 'b'] }
 * schema.validate([])          // { success: true, data: [] }
 * schema.validate([1, 2])      // { success: false, errors: [...] }
 * schema.validate('not array') // { success: false, errors: [...] }
 * ```
 */
export class ArrayType<T> extends BaseType<T[]> {
  constructor(private itemType: BaseType<T>) {
    super()
  }

  /**
   * Validates that the value is an array with valid items.
   *
   * @param value - The value to validate
   * @returns A ValidationResult with the array data or validation errors
   */
  validate(value: unknown): ValidationResult<T[]> {
    if (!Array.isArray(value)) {
      return this.failure('Expected array', 'invalid_type')
    }

    const errors: ValidationError[] = []
    const result: T[] = []

    for (let i = 0; i < value.length; i++) {
      const itemResult = this.itemType.validate(value[i])
      if (!itemResult.success) {
        // Prepend index to error paths
        itemResult.errors!.forEach((err) => {
          errors.push({ ...err, path: [String(i), ...err.path] })
        })
      } else {
        result.push(itemResult.data!)
      }
    }

    if (errors.length > 0) {
      return this.failures(errors)
    }
    return this.success(result)
  }
}

/**
 * Schema type for validating objects with a defined shape.
 *
 * Validates that the input is an object and validates each property
 * against the corresponding schema in the shape definition.
 * Unknown properties are stripped from the output.
 *
 * @typeParam T - The shape of the object
 *
 * @example
 * ```typescript
 * const schema = new ObjectType({ name: new StringType() })
 *
 * schema.validate({ name: 'John' })        // { success: true, data: { name: 'John' } }
 * schema.validate({ name: 123 })           // { success: false, errors: [...] }
 * schema.validate({})                       // { success: false, errors: [...] }
 * schema.validate({ name: 'John', extra: 1 }) // { success: true, data: { name: 'John' } }
 * ```
 */
export class ObjectType<T extends Record<string, unknown>> extends BaseType<T> {
  constructor(protected shape: { [K in keyof T]: BaseType<T[K]> }) {
    super()
  }

  /**
   * Validates that the value is an object matching the schema shape.
   *
   * @param value - The value to validate
   * @returns A ValidationResult with the object data or validation errors
   */
  validate(value: unknown): ValidationResult<T> {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) {
      return this.failure('Expected object', 'invalid_type')
    }

    const obj = value as Record<string, unknown>
    const errors: ValidationError[] = []
    const result: Record<string, unknown> = {}

    for (const [key, schema] of Object.entries(this.shape)) {
      const fieldValue = obj[key]
      if (fieldValue === undefined) {
        errors.push({ path: [key], message: 'Value is required', code: 'invalid_type' })
        continue
      }
      const fieldResult = (schema as BaseType<unknown>).validate(fieldValue)
      if (!fieldResult.success) {
        fieldResult.errors!.forEach((err) => {
          errors.push({ ...err, path: [key, ...err.path] })
        })
      } else {
        result[key] = fieldResult.data
      }
    }

    if (errors.length > 0) {
      return this.failures(errors)
    }
    return this.success(result as T)
  }

  /**
   * Converts this schema to a JSON Schema object.
   *
   * @returns A JSONSchema object representing this schema
   */
  toJSONSchema(): JSONSchema {
    const properties: Record<string, JSONSchema> = {}
    const required: string[] = []

    for (const [key, schema] of Object.entries(this.shape)) {
      properties[key] = this.typeToJSONSchema(schema as BaseType<unknown>)
      required.push(key)
    }

    return {
      type: 'object',
      properties,
      required,
      additionalProperties: false,
    }
  }

  /**
   * Converts a BaseType to its JSON Schema representation.
   */
  protected typeToJSONSchema(type: BaseType<unknown>): JSONSchema {
    let schema: JSONSchema
    if (type instanceof StringType) {
      schema = { type: 'string' }
    } else if (type instanceof NumberType) {
      schema = { type: 'number' }
    } else if (type instanceof BooleanType) {
      schema = { type: 'boolean' }
    } else if (type instanceof ArrayType) {
      schema = { type: 'array' }
    } else if (type instanceof ObjectType) {
      schema = type.toJSONSchema()
    } else {
      schema = { type: 'object' }
    }

    // Add AI hints to $comment if present
    const aiHints = type.getAIHints()
    if (aiHints) {
      schema.$comment = JSON.stringify({ ai: aiHints })
    }

    return schema
  }
}

// =============================================================================
// Reference Types
// =============================================================================

/**
 * Reference matching mode for $ref validation.
 *
 * - 'exact': Strict matching, rejects additional properties
 * - 'fuzzy': Loose matching, allows additional properties and hints
 */
export type ReferenceMode = 'exact' | 'fuzzy'

/**
 * Direction of the relationship reference.
 *
 * - 'forward': Outgoing relationship (this -> target)
 * - 'backward': Incoming relationship (target -> this)
 */
export type ReferenceDirection = 'forward' | 'backward'

/**
 * Parsed operator result for RefType.
 */
export interface RefOperator {
  direction: ReferenceDirection
  mode: ReferenceMode
  type: string
  isArray: boolean
}

/**
 * Shape of a reference object with $ref property.
 */
export interface RefObject {
  $ref: string
  [key: string]: unknown
}

/**
 * Regex pattern for parsing relationship operators in $.ref()
 * Matches: operator (-> | ~> | <- | <~) + PascalCase type name + optional array marker
 */
const REF_OPERATOR_REGEX = /^(->|~>|<-|<~)([A-Z][a-zA-Z0-9]*)(\[\])?$/

/**
 * Direction mapping for each operator
 */
const REF_DIRECTION_MAP: Record<string, ReferenceDirection> = {
  '->': 'forward',
  '~>': 'forward',
  '<-': 'backward',
  '<~': 'backward',
}

/**
 * Mode mapping for each operator
 */
const REF_MODE_MAP: Record<string, ReferenceMode> = {
  '->': 'exact',
  '~>': 'fuzzy',
  '<-': 'exact',
  '<~': 'fuzzy',
}

/**
 * Schema type for validating reference objects.
 *
 * References are objects with a $ref property that points to another resource.
 * Supports relationship operators:
 * - `->User` = forward exact relationship to User
 * - `~>User` = forward fuzzy (AI-discovered) relationship
 * - `<-User` = backward relationship from User
 * - `<~User` = backward fuzzy relationship
 * - `->User[]` = array of relationships
 *
 * Supports two modes:
 * - exact: Only $ref property allowed, strict type matching
 * - fuzzy: Additional properties allowed, supports semantic hints
 *
 * @example
 * ```typescript
 * const schema = new RefType('->User')
 *
 * // Exact mode (default)
 * schema.validate({ $ref: 'https://example.com/user/123' })
 * // { success: true, data: { $ref: '...' } }
 *
 * // Fuzzy mode allows extra properties
 * $.ref('~>Tag').validate({ $ref: '...', confidence: 0.9 })
 * // { success: true, data: { $ref: '...', confidence: 0.9 } }
 * ```
 */
export class RefType extends BaseType<RefObject | RefObject[]> {
  private mode: ReferenceMode = 'exact'
  private direction: ReferenceDirection = 'forward'
  private _isArray: boolean = false
  private _typeName: string

  /**
   * Creates a new RefType for the given type name or operator string.
   *
   * @param typeNameOrOperator - The type name (e.g., 'User') or operator string (e.g., '->User', '~>Tag[]')
   */
  constructor(typeNameOrOperator: string) {
    super()
    this._typeName = typeNameOrOperator
    this.parseOperator(typeNameOrOperator)
  }

  /**
   * Parse the operator string to extract direction, mode, type, and array flag.
   */
  private parseOperator(input: string): void {
    const match = input.match(REF_OPERATOR_REGEX)
    if (match) {
      const [, op, type, arrayMarker] = match
      this.direction = REF_DIRECTION_MAP[op]
      this.mode = REF_MODE_MAP[op]
      this._typeName = type
      this._isArray = !!arrayMarker
    } else {
      // Plain type name - default to forward exact
      this.direction = 'forward'
      this.mode = 'exact'
      this._isArray = false
    }
  }

  /**
   * Gets the type name this reference points to.
   *
   * @returns The type name string (without operator prefix)
   */
  getTypeName(): string {
    return this._typeName
  }

  /**
   * Gets the current reference matching mode.
   *
   * @returns The current mode ('exact' or 'fuzzy')
   */
  getMode(): ReferenceMode {
    return this.mode
  }

  /**
   * Gets the relationship direction.
   *
   * @returns The direction ('forward' or 'backward')
   */
  getDirection(): ReferenceDirection {
    return this.direction
  }

  /**
   * Returns whether this reference type expects an array.
   *
   * @returns true if array type, false otherwise
   */
  isArray(): boolean {
    return this._isArray
  }

  /**
   * Gets the parsed operator information.
   *
   * @returns The operator components
   */
  getOperator(): RefOperator {
    return {
      direction: this.direction,
      mode: this.mode,
      type: this._typeName,
      isArray: this._isArray,
    }
  }

  /**
   * Returns a new RefType with exact matching mode.
   *
   * In exact mode:
   * - Only the $ref property is allowed
   * - Additional properties cause validation failure
   *
   * @returns A new RefType configured for exact matching
   */
  exact(): RefType {
    const clone = this.clone()
    clone.mode = 'exact'
    return clone
  }

  /**
   * Returns a new RefType with fuzzy matching mode.
   *
   * In fuzzy mode:
   * - Additional properties are allowed
   * - Supports semantic hints like $type
   *
   * @returns A new RefType configured for fuzzy matching
   */
  fuzzy(): RefType {
    const clone = this.clone()
    clone.mode = 'fuzzy'
    return clone
  }

  /**
   * Creates a clone of this RefType with all current settings.
   */
  private clone(): RefType {
    const clone = new RefType(this._typeName)
    clone.mode = this.mode
    clone.direction = this.direction
    clone._isArray = this._isArray
    clone._description = this._description
    return clone
  }

  /**
   * Validates a single reference object.
   */
  private validateSingleRef(value: unknown): ValidationResult<RefObject> {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) {
      return this.failure(`Expected ${this._typeName} reference object`, 'invalid_type')
    }

    const obj = value as Record<string, unknown>

    if (!('$ref' in obj)) {
      return this.failure(`Expected $ref property for ${this._typeName}`, 'invalid_ref')
    }

    if (typeof obj.$ref !== 'string') {
      return this.failure('$ref must be a string', 'invalid_ref_type')
    }

    if (obj.$ref === '') {
      return this.failure('$ref cannot be empty', 'invalid_ref_empty')
    }

    // In exact mode, reject additional properties
    if (this.mode === 'exact') {
      const extraKeys = Object.keys(obj).filter((k) => k !== '$ref')
      if (extraKeys.length > 0) {
        return this.failure(`Unexpected property: ${extraKeys[0]}`, 'unexpected_property')
      }
    }

    return { success: true, data: obj as RefObject }
  }

  /**
   * Validates that the value is a valid reference object or array of references.
   *
   * @param value - The value to validate
   * @returns A ValidationResult with the RefObject(s) or validation errors
   */
  validate(value: unknown): ValidationResult<RefObject | RefObject[]> {
    if (this._isArray) {
      // Array validation
      if (!Array.isArray(value)) {
        return this.failure(`Expected array of ${this._typeName} references`, 'invalid_type')
      }

      const results: RefObject[] = []
      const errors: ValidationError[] = []

      for (let i = 0; i < value.length; i++) {
        const itemResult = this.validateSingleRef(value[i])
        if (itemResult.success) {
          results.push(itemResult.data)
        } else {
          // Prepend index to error paths
          itemResult.errors!.forEach((err) => {
            errors.push({ ...err, path: [String(i), ...err.path] })
          })
        }
      }

      if (errors.length > 0) {
        return { success: false, errors }
      }

      return { success: true, data: results }
    }

    // Single reference validation
    return this.validateSingleRef(value)
  }

  /**
   * Converts this RefType to JSON Schema representation.
   *
   * @returns A JSONSchema object with DO metadata extensions
   */
  toJSONSchema(): JSONSchema & Record<string, unknown> {
    const refSchema: JSONSchema & Record<string, unknown> = {
      type: 'object',
      properties: {
        $ref: { type: 'string' },
      },
      required: ['$ref'],
      additionalProperties: this.mode === 'fuzzy',
    }

    // Add AI/DO metadata
    refSchema['x-do-mode'] = this.mode
    refSchema['x-do-direction'] = this.direction
    refSchema['x-do-target-type'] = this._typeName

    if (this.mode === 'fuzzy') {
      refSchema['x-do-ai-discoverable'] = true
    }

    if (this._description) {
      refSchema.description = this._description
    }

    if (this._isArray) {
      return {
        type: 'array',
        items: refSchema,
        'x-do-mode': this.mode,
        'x-do-direction': this.direction,
        'x-do-target-type': this._typeName,
        'x-do-ai-discoverable': this.mode === 'fuzzy' ? true : undefined,
      }
    }

    return refSchema
  }
}

// =============================================================================
// Schema Type Class (Fluent Builder)
// =============================================================================

/**
 * Schema type for building object schemas with fluent API.
 *
 * Provides methods like strict(), passthrough(), partial(), pick(), omit(),
 * extend(), merge(), and required() for composing schemas.
 *
 * @typeParam T - The shape of the object
 *
 * @example
 * ```typescript
 * const schema = new SchemaType({ name: new StringType() })
 *   .strict()
 *   .partial()
 *
 * schema.validate({ name: 'John' })  // { success: true, data: { name: 'John' } }
 * ```
 */
export class SchemaType<T extends Record<string, unknown>> extends BaseType<T> {
  private strictMode = false
  private passthroughMode = false
  private partialMode = false

  constructor(private shape: { [K in keyof T]: BaseType<T[K]> }) {
    super()
  }

  /**
   * Validates that the value is an object matching the schema shape.
   */
  validate(value: unknown): ValidationResult<T> {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) {
      return this.failure('Expected object', 'invalid_type')
    }

    const obj = value as Record<string, unknown>
    const errors: ValidationError[] = []
    const result: Record<string, unknown> = {}

    // Check for unrecognized keys in strict mode
    if (this.strictMode) {
      const schemaKeys = new Set(Object.keys(this.shape))
      for (const key of Object.keys(obj)) {
        if (!schemaKeys.has(key) && key !== '__proto__') {
          errors.push({ path: [key], message: `Unrecognized key: ${key}`, code: 'unrecognized_keys' })
        }
      }
    }

    for (const [key, schema] of Object.entries(this.shape)) {
      const fieldValue = obj[key]
      if (fieldValue === undefined) {
        if (!this.partialMode) {
          errors.push({ path: [key], message: 'Value is required', code: 'required' })
        }
        continue
      }
      const fieldResult = (schema as BaseType<unknown>).validate(fieldValue)
      if (!fieldResult.success) {
        fieldResult.errors!.forEach((err) => {
          errors.push({ ...err, path: [key, ...err.path] })
        })
      } else {
        result[key] = fieldResult.data
      }
    }

    // Passthrough extra properties
    if (this.passthroughMode) {
      for (const key of Object.keys(obj)) {
        if (!(key in this.shape) && key !== '__proto__') {
          result[key] = obj[key]
        }
      }
    }

    if (errors.length > 0) {
      return this.failures(errors)
    }
    return this.success(result as T)
  }

  /**
   * Makes the schema reject objects with unknown keys.
   */
  strict(): SchemaType<T> {
    const clone = this.clone()
    clone.strictMode = true
    return clone
  }

  /**
   * Makes the schema pass through unknown keys to the output.
   */
  passthrough(): SchemaType<T> {
    const clone = this.clone()
    clone.passthroughMode = true
    return clone
  }

  /**
   * Makes all fields optional.
   */
  partial(): SchemaType<Partial<T>> {
    const clone = this.clone() as unknown as SchemaType<Partial<T>>
    clone.partialMode = true
    return clone
  }

  /**
   * Makes all fields required (reverses partial()).
   */
  required(): SchemaType<Required<T>> {
    const clone = this.clone() as unknown as SchemaType<Required<T>>
    clone.partialMode = false
    return clone
  }

  /**
   * Creates a new schema with only the specified keys.
   */
  pick<K extends keyof T>(keys: K[]): SchemaType<Pick<T, K>> {
    const newShape: Record<string, BaseType<unknown>> = {}
    for (const key of keys) {
      if (key in this.shape) {
        newShape[key as string] = this.shape[key] as BaseType<unknown>
      }
    }
    const clone = new SchemaType(newShape as { [P in K]: BaseType<T[P]> })
    clone.strictMode = this.strictMode
    clone.passthroughMode = this.passthroughMode
    clone.partialMode = this.partialMode
    return clone as unknown as SchemaType<Pick<T, K>>
  }

  /**
   * Creates a new schema without the specified keys.
   */
  omit<K extends keyof T>(keys: K[]): SchemaType<Omit<T, K>> {
    const keysToOmit = new Set(keys as string[])
    const newShape: Record<string, BaseType<unknown>> = {}
    for (const [key, schema] of Object.entries(this.shape)) {
      if (!keysToOmit.has(key)) {
        newShape[key] = schema as BaseType<unknown>
      }
    }
    const clone = new SchemaType(newShape as { [P in Exclude<keyof T, K>]: BaseType<T[P]> })
    clone.strictMode = this.strictMode
    clone.passthroughMode = this.passthroughMode
    clone.partialMode = this.partialMode
    return clone as unknown as SchemaType<Omit<T, K>>
  }

  /**
   * Creates a new schema with additional fields.
   */
  extend<U extends Record<string, unknown>>(
    shape: { [K in keyof U]: BaseType<U[K]> }
  ): SchemaType<T & U> {
    const newShape = { ...this.shape, ...shape } as { [K in keyof (T & U)]: BaseType<(T & U)[K]> }
    const clone = new SchemaType(newShape)
    clone.strictMode = this.strictMode
    clone.passthroughMode = this.passthroughMode
    clone.partialMode = this.partialMode
    return clone
  }

  /**
   * Merges this schema with another schema.
   */
  merge<U extends Record<string, unknown>>(other: SchemaType<U>): SchemaType<T & U> {
    const newShape = { ...this.shape, ...other.shape } as { [K in keyof (T & U)]: BaseType<(T & U)[K]> }
    const clone = new SchemaType(newShape)
    clone.strictMode = this.strictMode || other.strictMode
    clone.passthroughMode = this.passthroughMode || other.passthroughMode
    clone.partialMode = this.partialMode && other.partialMode
    return clone
  }

  private clone(): SchemaType<T> {
    const clone = new SchemaType(this.shape)
    clone.strictMode = this.strictMode
    clone.passthroughMode = this.passthroughMode
    clone.partialMode = this.partialMode
    return clone
  }

  // ==========================================================================
  // Schema Introspection Methods
  // ==========================================================================

  /**
   * Returns the list of field names in this schema.
   *
   * @returns An array of field names
   *
   * @example
   * ```typescript
   * const schema = $.schema({ name: $.string(), age: $.number() })
   * schema.getFields() // ['name', 'age']
   * ```
   */
  getFields(): (keyof T)[] {
    return Object.keys(this.shape) as (keyof T)[]
  }

  /**
   * Returns the type validator for a specific field.
   *
   * @param name - The field name to get the type for
   * @returns The BaseType validator for the field, or undefined if not found
   *
   * @example
   * ```typescript
   * const schema = $.schema({ name: $.string(), age: $.number() })
   * schema.getFieldType('name') // StringType instance
   * schema.getFieldType('unknown') // undefined
   * ```
   */
  getFieldType<K extends keyof T>(name: K): BaseType<T[K]> | undefined {
    return this.shape[name]
  }

  /**
   * Checks if a field is required (i.e., not in partial mode).
   *
   * @param name - The field name to check
   * @returns true if the field is required, false if optional or not found
   *
   * @example
   * ```typescript
   * const schema = $.schema({ name: $.string() })
   * schema.isRequired('name') // true
   * schema.partial().isRequired('name') // false
   * ```
   */
  isRequired<K extends keyof T>(name: K): boolean {
    if (!(name in this.shape)) {
      return false
    }
    return !this.partialMode
  }

  /**
   * Returns the full shape definition of this schema.
   *
   * @returns The shape object mapping field names to their validators
   *
   * @example
   * ```typescript
   * const schema = $.schema({ name: $.string(), age: $.number() })
   * const shape = schema.getShape()
   * // { name: StringType, age: NumberType }
   * ```
   */
  getShape(): { [K in keyof T]: BaseType<T[K]> } {
    return { ...this.shape }
  }

  /**
   * Converts this schema to a JSON Schema object.
   */
  toJSONSchema(): JSONSchema {
    const properties: Record<string, JSONSchema> = {}
    const required: string[] = []

    for (const [key, schema] of Object.entries(this.shape)) {
      properties[key] = this.typeToJSONSchema(schema as BaseType<unknown>)
      if (!this.partialMode) {
        required.push(key)
      }
    }

    const result: JSONSchema = {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties,
      required,
      additionalProperties: false,
    }

    // Add schema-level description if present
    if (this._description) {
      result.description = this._description
    }

    return result
  }

  private typeToJSONSchema(type: BaseType<unknown>): JSONSchema {
    let schema: JSONSchema
    if (type instanceof StringType) {
      schema = { type: 'string' }
    } else if (type instanceof NumberType) {
      schema = { type: 'number' }
    } else if (type instanceof BooleanType) {
      schema = { type: 'boolean' }
    } else if (type instanceof ArrayType) {
      schema = { type: 'array' }
    } else if (type instanceof ObjectType || type instanceof SchemaType) {
      schema = (type as SchemaType<Record<string, unknown>>).toJSONSchema()
    } else {
      schema = { type: 'object' }
    }

    // Add description if present
    const description = type.getDescription()
    if (description) {
      schema.description = description
    }

    // Add examples if present
    const examples = type.getExamples()
    if (examples && examples.length > 0) {
      schema.examples = examples
    }

    // Add AI hints to $comment if present
    const aiHints = type.getAIHints()
    if (aiHints) {
      schema.$comment = JSON.stringify({ ai: aiHints })
    }

    return schema
  }
}
